services:
  mysql:
    image: mysql:8.0
    container_name: taskapp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: taskapp
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: taskapp-phpmyadmin
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    ports:
      - "8082:80"

  backend:
    build: ./backend
    container_name: taskapp-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/taskapp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - mysql
    ports:
      - "8081:8081"

  frontend:
    build: ./frontend
    container_name: taskapp-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  mysql_data: